#Enable forge global version checking
versionCheck = true
splashscreen = true
#Default config path for servers
defaultConfigPath = "defaultconfigs"
#Disables Optimized DFU client-side - already disabled on servers
disableOptimizedDFU = true
#Max threads for early initialization parallelism,  -1 is based on processor count
maxThreads = -1

